notifications:
  email: false
git:
  quiet: true
  depth: false
language: java
jdk: openjdk11
node_js: lts/*
python: 3.7
matrix:
  include:
    - python: 3.7
services:
  - xvfb
  - docker
addons:
  apt:
    update: false
    packages:
      - jq
      - bash
      - curl
      - tree
      - docker-ce
      - libxml2-utils
      - libappindicator1
      - fonts-liberation
      - google-chrome-stable
      - python3-setuptools
      - python3-pip
install: true
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  #
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  - stop_any 80 5432 8080
  #
  - export PATH=$HOME/.local/bin:$PATH
  - pip -V
  - docker-compose version
  - pip3 install --user --upgrade pip
  - pip install --user --upgrade httpie docker-compose
  - http --version --debug
  - pip -V
  #
  - stop_any 80 8080 5432
  - docker-compose version
env:
  global:
    - TERM=dumb
jobs:
  include:
    - stage: test
      name: boot-your-reactor-kotlin-coroutines opernjdk11
      jdk: openjdk11
      script: ./gradlew
    - stage: test
      jdk: openjdk13
      name: boot-your-reactor-kotlin-coroutines opernjdk13
      script: ./gradlew
    - stage: test
      name: bot opernjdk11
      jdk: openjdk11
      script:
        - ./gradlew -b bot/build.gradle.kts
        - java -jar bot/build/libs/*.jar
    - stage: test
      name: bot opernjdk11 bash
      jdk: openjdk11
      script:
        - ./gradlew -b bot/build.gradle.kts
        - bash bot/build/libs/*.jar
    - stage: test
      name: bot opernjdk13
      jdk: openjdk13
      script:
        - ./gradlew -b bot/build.gradle.kts
        - java -jar bot/build/libs/*.jar
    - stage: test
      name: bot opernjdk13 bash
      jdk: openjdk13
      script:
        - ./gradlew -b bot/build.gradle.kts
        - bash bot/build/libs/*.jar
    - stage: test
      name: user-message opernjdk11 bash
      jdk: openjdk11
      script:
        - ./gradlew -b user-message/build.gradle.kts
        - bash user-message/build/libs/*.jar &
        - wait_for 8080
        - http :8080/actuator
        - http :8080/actuator/health
        - sleep 1s
        - stop_any 80 8080
    - stage: test
      jdk: openjdk13
      name: gradle opernjdk13
      script: ./gradlew dependencyUpdates -Drevision=release
      after_script: cat build/dependencyUpdates/report.txt
    - stage: deploy
      name: VuePress documentation deployment
      node_js: lts/*
      script: skip
      before_deploy:
        - cd $TRAVIS_BUILD_DIR/docs && npm i
        - cd $TRAVIS_BUILD_DIR/docs && npm run gh-pages
      env:
        # travis encrypt GITHUB_TOKEN=ololo-trololo
        - secure: "n3/ZYgUxU2odhmf7dA/UQVWzaNLirxixAA1zg7unQA5mKLfsGR/R3PrBJ+/YJk1mczMGoNxfo20Sox+qI6aJvHTA5jqg7510poFdmQNa5VudONs+znvkACQ1mYL2wK29/gkM4e8gId8rTEkmbodTF1gka0bJYezLLPaVIN2LdwXScnez64T5Yun31zc/910CcrfTn3TOnA0kSzmf/0FYbaP2NmyRubGp5FB8pdryWXmk+UlTysbGHUod6E/t6QyjerxkSu8hZZYzF96U2xrJHff2EKZA3XkOc29peRtKguSnobF7Yf/8h+XvXcMx/x4ORGxp67uWvxz967lIVDqAL0JF4UskImDqjliHsJB8gu5IHfk60QTZjQMuVUSFvf/tz+kqgEu40c/AzxlZQftSsk9gPrJDVuVQjJSwmtFg5KFaNe2tvmP7c9lyQZWnVDd0GWmsCE6DQysEqAYpRpQui5k2ZCdZO2R67XTqZZYAJFzkYdiwRqsNKWII8mR0P5paD3FtnpgHblEal4x8teuME4uKPOaqHQ4iozIwJTXOjhgoAinVu9HisjK8wi2g8aEJpwx9s7lPZ0iMeES7DulON9thIL49iTbTFjnOzonnh6xM32AJqcBFUdR+VHLO3ciR+cun3HKvK0wJcIXgeGRzohkhwTsK3glbZAJiMT7H3uY="
      deploy: &pages
        provider: pages
        github-token: "$GITHUB_TOKEN"
        local-dir: docs/.vuepress/dist
        # require gh-pages to be created manually first before deployment!
        target_branch: gh-pages
        skip_cleanup: true
        keep-history: true
        on:
          branch: master
          condition: "$TRAVIS_PULL_REQUEST = false"
before_cache:
  - for i in `find ~/.gradle -name '*.lock' -type file` ; do rm -rfv $i ; done
cache:
  directories:
    - ./docs/node_modules
    - ~/.local/daggerok
    - ~/.gradle
    - ~/.docker
    - ~/.n*
  packages: true
  npm: true
