DROP TABLE IF EXISTS city;
CREATE TABLE user (
  id    BIGINT IDENTITY NOT NULL PRIMARY KEY,
  name  VARCHAR(30),
);
DROP TABLE IF EXISTS message;
CREATE TABLE message (
  id    BIGINT IDENTITY NOT NULL PRIMARY KEY,
  body  VARCHAR(30),
);
